# Generated by Django 5.0.1 on 2024-01-26 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Celebrity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('language', models.CharField(max_length=150)),
                ('birthday', models.DateField()),
                ('hobby', models.CharField(max_length=250)),
                ('follow', models.URLField()),
                ('image', models.ImageField(blank=True, upload_to='celebrity')),
            ],
        ),
    ]
