# Generated by Django 5.0.1 on 2024-01-28 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebrity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celebrity',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/db_images'),
        ),
    ]
