# Generated by Django 5.0.1 on 2024-01-26 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='celebrity'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_year',
            field=models.DateField(auto_now_add=True),
        ),
    ]
